sonar.projectKey=LegumexStore-frontend
sonar.projectName=LegumexStore Frontend
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.token=sqa_29e7a8b6360b63c08c7d684e7cd0c7190bf9a346
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.tsx,**/*.test.ts,**/coverage/**